### ISSUE TITLE
/contact-me cannot submit email

### ISSUE THREAD

**Issue by EthanEFung** [lbain/lucybain#2]
@lbain , it seems to be that in my firefox browser, the email input on the contact-me page is disabled.

**Comment by lbain** [comment]
Hi @EthanEFung,
Thanks for the bug report! I just tested this and it worked fine for me (57.0.4). Which version of FF were you using? Could you try it in [incognito](https://support.mozilla.org/en-US/kb/private-browsing-use-firefox-without-history) mode to check if any extensions were causing problems?

Thanks!
Lucy

**Comment by EthanEFung** [comment]
@lbain works fine now. Not entirely sure what happened, but it might have been an extension of mine. FF 58.0.2
